name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- BUILD AND LOAD LOCALLY FOR INSPECTION ----------
      - name: Build (load for inspection)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: test/wan22:inspect

      # ---------- CHECK THAT BOOTSTRAP IS INSIDE THE IMAGE ----------
      - name: Inspect image for bootstrap
        run: |
          echo "Checking that /usr/local/bin/wan22_bootstrap.sh exists..."
          docker run --rm --entrypoint bash test/wan22:inspect -lc "
            set -e;
            echo '=== Should exist:';
            ls -l /usr/local/bin/wan22_bootstrap.sh || (echo 'FATAL: bootstrap missing!' && exit 1);
            echo;
            echo '=== /workspace listing:';
            ls -la /workspace | sed -n '1,120p';
          "

      # ---------- IF INSPECTION PASSES, BUILD AND PUSH ----------
      - name: Build and Push (final)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wan22:latest
