name: Build, Inspect, and Push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (load into runner for inspection)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true         # <- load locally so we can 'docker run' it
          tags: test/wan22:inspect

      - name: Diagnose image contents
        run: |
          echo ">>> Listing /workspace from inside container"
          docker run --rm --entrypoint bash test/wan22:inspect -lc "ls -la /workspace; echo '---'; test -f /workspace/wan22_bootstrap.sh && echo 'bootstrap present' || echo 'bootstrap MISSING'; test -f /workspace/app.py && echo 'app present' || echo 'app MISSING'"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
