name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Free disk on the runner
      - name: Maximize build space
        run: |
          echo "=== Before cleanup ==="
          df -h
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/share/dotnet || true
          sudo apt-get clean || true
          sudo rm -rf /var/lib/apt/lists/* || true
          sudo docker system prune -af || true
          echo "=== After cleanup ==="
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Tiny precheck stage (does not build heavy layers)
      - name: Precheck bootstrap presence
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: precheck
          load: true
          tags: test/wan22:precheck

      # Build & push final image directly (no local load)
      - name: Build and Push (final)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wan22:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
